blank_issues_enabled: true
contact_links:
  - name: Forum
    url: https://community.gladysassistant.com/
    about: We use this forum for questions & support.
  - name: Feature Requests
    url: https://community.gladysassistant.com/c/feature-requests/43
    about: We use our forum as feature requests. You can create feature requests there, and vote for them.
